texts = {
    'de': {
        'window_title': "🎵 YouTube Downloader",
        'youtube_link': "YouTube Link:",
        'url_placeholder': "YouTube Video oder Playlist Link hier eingeben...",
        'url_tooltip': "Füge hier die URL vom YouTube-Video oder Playlist ein.",
        'folder_tooltip': "Ordner auswählen, in dem die Dateien gespeichert werden",
        'btn_folder': "📁 Zielordner wählen",
        'btn_folder_tooltip': "Wähle den Speicherort für die Dateien",
        'btn_open_folder': "📂 Öffnen",
        'btn_open_folder_tooltip': "Öffne den ausgewählten Ausgabeordner",
        'mp3_quality': "Qualität (kbps):",
        'quality_tooltip': "Bitrate der Audiodatei. Höhere Werte = bessere Qualität, größere Dateien.",
        'quality_combo_tooltip': "Wähle die Bitrate (kbps).\n128 = kleinere Dateien, 320 = höhere Qualität",
        'playlist_checkbox': "Playlist herunterladen",
        'playlist_tooltip': "Wenn aktiviert, werden alle Videos einer YouTube-Playlist heruntergeladen.\nSonst nur das einzelne Video.",
        'format_label': "Format:",
        'format_combo_tooltip': "Wähle das Ausgabeformat (Audio/Video).",
        'embed_metadata': "Metadaten einbetten",
        'embed_metadata_tooltip': "ID3/Metadaten (Titel, Interpret, Album) in die Audiodatei schreiben.",
        'save_thumbnail': "Thumbnail speichern / einbetten",
        'save_thumbnail_tooltip': "Speichert das Video-Cover/Thumbnail und bettet es evtl. in die Audiodatei ein.",
        'auto_open': "Ordner nach Ende öffnen",
        'auto_open_tooltip': "Öffnet automatisch den Zielordner, wenn der Download fertig ist.",
        'status_downloading': "🔄 Download läuft...",
        'btn_start': "▶ Download starten",
        'btn_start_tooltip': "Starte den Download-Prozess",
        'btn_stop': "■ Stop",
        'btn_stop_tooltip': "Stoppe den laufenden Download",
        'msg_no_url': "Bitte einen gültigen Link eingeben!",
        'msg_done': "Die Datei wurde erfolgreich gespeichert.",
        'msg_error': "Fehler aufgetreten.",
        'msg_download_stopped': "Download wurde gestoppt.",
        'language_label': "Sprache:"
    },
    'en': {
        'window_title': "🎵 YouTube Downloader",
        'youtube_link': "YouTube Link:",
        'url_placeholder': "Enter YouTube video or playlist link here...",
        'url_tooltip': "Paste here the URL of the YouTube video or playlist.",
        'folder_tooltip': "Select folder where files will be saved",
        'btn_folder': "📁 Choose folder",
        'btn_folder_tooltip': "Select the save location for the files",
        'btn_open_folder': "📂 Open",
        'btn_open_folder_tooltip': "Open the selected output folder",
        'mp3_quality': "Quality (kbps):",
        'quality_tooltip': "Bitrate of the audio file. Higher means better quality, bigger size.",
        'quality_combo_tooltip': "Choose bitrate (kbps).\n128 = smaller files, 320 = higher quality",
        'playlist_checkbox': "Download playlist",
        'playlist_tooltip': "If enabled, all videos in a YouTube playlist will be downloaded.\nOtherwise only the single video.",
        'format_label': "Format:",
        'format_combo_tooltip': "Choose the output format (audio/video).",
        'embed_metadata': "Embed metadata",
        'embed_metadata_tooltip': "Write ID3/metadata (title, artist, album) into the audio file.",
        'save_thumbnail': "Save/Embed thumbnail",
        'save_thumbnail_tooltip': "Save the video thumbnail and optionally embed it into the audio file.",
        'auto_open': "Auto-open folder when done",
        'auto_open_tooltip': "Automatically open the output folder after download completes.",
        'status_downloading': "🔄 Downloading...",
        'btn_start': "▶ Start download",
        'btn_start_tooltip': "Start the download process",
        'btn_stop': "■ Stop",
        'btn_stop_tooltip': "Stop the running download",
        'msg_no_url': "Please enter a valid URL!",
        'msg_done': "The file was saved successfully.",
        'msg_error': "An error occurred.",
        'msg_download_stopped': "Download was stopped.",
        'language_label': "Language:"
    }
}
