texts = {
    "de": {
        "window_title": "YouTube Downloader",
        "youtube_link": "YouTube-Link:",
        "url_placeholder": "YouTube-Video- oder Playlist-Link hier eingeben...",
        "url_tooltip": "Füge hier die URL eines YouTube-Videos oder einer Playlist ein.",
        "folder_tooltip": "Wähle den Ordner aus, in dem die Dateien gespeichert werden sollen.",
        "btn_folder": "Zielordner wählen",
        "btn_folder_tooltip": "Wählt den Speicherort für Downloads aus.",
        "btn_open_folder": "Ordner öffnen",
        "btn_open_folder_tooltip": "Öffnet den aktuell ausgewählten Ausgabeordner.",
        "mp3_quality": "Qualität (kbps):",
        "quality_tooltip": "Höhere Bitraten liefern bessere Audioqualität, erzeugen aber größere Dateien.",
        "quality_combo_tooltip": "Wähle die gewünschte Audio-Bitrate aus.",
        "playlist_checkbox": "Playlist herunterladen",
        "playlist_tooltip": "Wenn aktiviert, werden alle Videos einer Playlist heruntergeladen.",
        "format_label": "Format:",
        "format_combo_tooltip": "Wähle das gewünschte Ausgabeformat.",
        "resolution_label": "Auflösung:",
        "resolution_tooltip": "Nur für MP4 relevant. Wählt die bevorzugte Videoauflösung.",
        "resolution_combo_tooltip": "Falls die Auflösung nicht verfügbar ist, wird die nächstbeste Variante genutzt.",
        "embed_metadata": "Metadaten einbetten",
        "embed_metadata_tooltip": "Schreibt Titel, Artist und weitere Infos in die Ausgabedatei.",
        "save_thumbnail": "Thumbnail speichern / einbetten",
        "save_thumbnail_tooltip": "Speichert das Thumbnail und bettet es bei unterstützten Formaten ein.",
        "auto_open": "Ordner nach Abschluss öffnen",
        "auto_open_tooltip": "Öffnet den Zielordner automatisch nach einem erfolgreichen Download.",
        "status_idle": "Bereit",
        "status_preparing": "Download wird vorbereitet...",
        "status_converting": "Nachbearbeitung läuft...",
        "status_done": "Fertig",
        "status_stopped": "Gestoppt",
        "status_error": "Fehler aufgetreten",
        "status_ffmpeg_missing": "FFmpeg fehlt",
        "btn_start": "Download starten",
        "btn_start_tooltip": "Startet den Download-Prozess.",
        "btn_stop": "Stop",
        "btn_stop_tooltip": "Stoppt den aktuellen Download.",
        "msg_no_url": "Bitte gib einen gültigen YouTube-Link ein.",
        "msg_invalid_folder": "Bitte wähle einen existierenden Ausgabeordner aus.",
        "msg_done": "Die Datei wurde erfolgreich gespeichert.",
        "msg_error": "Es ist ein Fehler aufgetreten.",
        "msg_download_stopped": "Der Download wurde gestoppt.",
        "msg_ffmpeg_missing": "FFmpeg wurde nicht gefunden. Konvertierung, Thumbnail-Einbettung oder MP4-Merge funktionieren ohne FFmpeg nicht.",
        "msg_ffmpeg_required": "FFmpeg wurde nicht gefunden. Installiere FFmpeg und füge es dem PATH hinzu.",
        "msg_folder_missing": "Der ausgewählte Ordner existiert nicht.",
        "msg_folder_open_failed": "Ordner konnte nicht geöffnet werden:",
        "msg_settings_reset": "Die Einstellungen waren beschädigt und wurden auf Standardwerte zurückgesetzt.",
        "msg_bad_settings_backup": "Defekte Einstellungen wurden als .broken-Datei gesichert.",
        "language_label": "Sprache:",
        "version_label": "Version: {version} | Entwickler: {developer}",
        "progress_label": "Fortschritt",
        "log_label": "Download-Protokoll",
        "log_placeholder": "Download-Protokoll erscheint hier...",
        "ffmpeg_missing_title": "FFmpeg nicht gefunden",
        "download_complete_title": "Abgeschlossen",
        "error_title": "Fehler",
        "missing_link_title": "Link fehlt",
        "invalid_folder_title": "Ungültiger Ordner",
        "folder_not_found_title": "Ordner nicht gefunden",
        "open_folder_failed_title": "Ordner konnte nicht geöffnet werden",
        "settings_reset_title": "Einstellungen zurückgesetzt",
        "ffmpeg_detected": "FFmpeg erkannt: {path}",
        "prefetch_failed": "Videoinfos konnten nicht vorgeladen werden: {error}",
        "title_loaded": "Titel geladen: {title}",
        "playlist_loaded": "Playlist geladen: {title} ({count} Einträge)",
        "disk_space_error": "Nicht genug Speicherplatz für diese Playlist. Download abgebrochen.",
        "download_starting": "Download startet ({format})",
        "download_stopped_log": "Download wurde vom Benutzer gestoppt.",
        "all_done_log": "Alles erledigt.",
        "error_log": "Fehler: {error}",
        "download_label": "Download",
        "ready_for_download": "Bereit für den nächsten Download.",
        "format_info_audio": "Audio-Ausgabe mit optionaler Konvertierung über FFmpeg.",
        "format_info_video": "Video-Ausgabe als MP4 mit Video+Audio-Merge über FFmpeg.",
    },
    "en": {
        "window_title": "YouTube Downloader",
        "youtube_link": "YouTube Link:",
        "url_placeholder": "Enter a YouTube video or playlist link here...",
        "url_tooltip": "Paste the URL of a YouTube video or playlist here.",
        "folder_tooltip": "Choose the folder where downloaded files will be saved.",
        "btn_folder": "Choose folder",
        "btn_folder_tooltip": "Select the output folder for downloads.",
        "btn_open_folder": "Open folder",
        "btn_open_folder_tooltip": "Open the currently selected output folder.",
        "mp3_quality": "Quality (kbps):",
        "quality_tooltip": "Higher bitrates improve audio quality but create larger files.",
        "quality_combo_tooltip": "Choose the desired audio bitrate.",
        "playlist_checkbox": "Download playlist",
        "playlist_tooltip": "When enabled, all videos from a playlist will be downloaded.",
        "format_label": "Format:",
        "format_combo_tooltip": "Choose the desired output format.",
        "resolution_label": "Resolution:",
        "resolution_tooltip": "Only relevant for MP4. Chooses the preferred video resolution.",
        "resolution_combo_tooltip": "If the resolution is unavailable, the nearest matching stream is used.",
        "embed_metadata": "Embed metadata",
        "embed_metadata_tooltip": "Writes title, artist, and related info into the output file.",
        "save_thumbnail": "Save / embed thumbnail",
        "save_thumbnail_tooltip": "Saves the thumbnail and embeds it when supported.",
        "auto_open": "Open folder when finished",
        "auto_open_tooltip": "Automatically opens the output folder after a successful download.",
        "status_idle": "Ready",
        "status_preparing": "Preparing download...",
        "status_converting": "Post-processing...",
        "status_done": "Done",
        "status_stopped": "Stopped",
        "status_error": "An error occurred",
        "status_ffmpeg_missing": "FFmpeg missing",
        "btn_start": "Start download",
        "btn_start_tooltip": "Start the download process.",
        "btn_stop": "Stop",
        "btn_stop_tooltip": "Stop the current download.",
        "msg_no_url": "Please enter a valid YouTube link.",
        "msg_invalid_folder": "Please choose an existing output folder.",
        "msg_done": "The file was saved successfully.",
        "msg_error": "An error occurred.",
        "msg_download_stopped": "The download was stopped.",
        "msg_ffmpeg_missing": "FFmpeg was not found. Conversion, thumbnail embedding, or MP4 merging will fail without FFmpeg.",
        "msg_ffmpeg_required": "FFmpeg was not found. Install FFmpeg and add it to PATH.",
        "msg_folder_missing": "The selected folder does not exist.",
        "msg_folder_open_failed": "Could not open folder:",
        "msg_settings_reset": "Settings were corrupted and have been reset to defaults.",
        "msg_bad_settings_backup": "Broken settings were preserved as a .broken file.",
        "language_label": "Language:",
        "version_label": "Version: {version} | Developer: {developer}",
        "progress_label": "Progress",
        "log_label": "Download log",
        "log_placeholder": "Download log will appear here...",
        "ffmpeg_missing_title": "FFmpeg not found",
        "download_complete_title": "Complete",
        "error_title": "Error",
        "missing_link_title": "Missing link",
        "invalid_folder_title": "Invalid folder",
        "folder_not_found_title": "Folder not found",
        "open_folder_failed_title": "Could not open folder",
        "settings_reset_title": "Settings reset",
        "ffmpeg_detected": "FFmpeg detected: {path}",
        "prefetch_failed": "Could not pre-fetch video info: {error}",
        "title_loaded": "Title loaded: {title}",
        "playlist_loaded": "Playlist loaded: {title} ({count} items)",
        "disk_space_error": "Not enough disk space for this playlist. Download aborted.",
        "download_starting": "Starting download ({format})",
        "download_stopped_log": "Download stopped by user.",
        "all_done_log": "All done.",
        "error_log": "Error: {error}",
        "download_label": "Download",
        "ready_for_download": "Ready for the next download.",
        "format_info_audio": "Audio output with optional FFmpeg conversion.",
        "format_info_video": "Video output as MP4 with FFmpeg video+audio merging.",
    },
}
