texts = {
    'de': {
        'window_title': "🎵 YouTube MP3 Downloader",
        'youtube_link': "YouTube Link:",
        'url_placeholder': "YouTube Video oder Playlist Link hier eingeben...",
        'url_tooltip': "Füge hier die URL vom YouTube-Video oder Playlist ein.",
        'folder_tooltip': "Ordner auswählen, in dem die MP3s gespeichert werden",
        'btn_folder': "📁 Zielordner wählen",
        'btn_folder_tooltip': "Wähle den Speicherort für die MP3-Dateien",
        'mp3_quality': "MP3 Qualität:",
        'quality_tooltip': "Bitrate der MP3-Datei. Höhere Werte = bessere Qualität, größere Dateien.",
        'quality_combo_tooltip': "Wähle die Bitrate für die MP3 (kbps).\n128 = Grundqualität (kleiner), 320 = HQ (größer)",
        'playlist_checkbox': "Playlist herunterladen",
        'playlist_tooltip': "Wenn aktiviert, werden alle Videos einer YouTube-Playlist heruntergeladen.\nSonst nur das einzelne Video.",
        'status_downloading': "🔄 Download läuft...",
        'btn_start': "▶ Download starten",
        'btn_start_tooltip': "Starte den Download-Prozess",
        'btn_stop': "■ Stop",
        'btn_stop_tooltip': "Stoppe den laufenden Download",
        'msg_no_url': "Bitte einen gültigen YouTube-Link eingeben!",
        'msg_done': "Deine MP3 wurde erfolgreich gespeichert.",
        'msg_error': "Fehler aufgetreten.",
        'msg_download_stopped': "Download wurde gestoppt.",
        'language_label': "Sprache:"
    },
    'en': {
        'window_title': "🎵 YouTube MP3 Downloader",
        'youtube_link': "YouTube Link:",
        'url_placeholder': "Enter YouTube video or playlist link here...",
        'url_tooltip': "Paste here the URL of the YouTube video or playlist.",
        'folder_tooltip': "Select folder where MP3 files will be saved",
        'btn_folder': "📁 Choose folder",
        'btn_folder_tooltip': "Select the save location for the MP3 files",
        'mp3_quality': "MP3 Quality:",
        'quality_tooltip': "Bitrate of the MP3 file. Higher means better quality, bigger size.",
        'quality_combo_tooltip': "Choose bitrate for MP3 (kbps).\n128 = low, 320 = high quality",
        'playlist_checkbox': "Download playlist",
        'playlist_tooltip': "If enabled, all videos in a YouTube playlist will be downloaded.\nOtherwise only the single video.",
        'status_downloading': "🔄 Downloading...",
        'btn_start': "▶ Start download",
        'btn_start_tooltip': "Start the download process",
        'btn_stop': "■ Stop",
        'btn_stop_tooltip': "Stop the running download",
        'msg_no_url': "Please enter a valid YouTube link!",
        'msg_done': "Your MP3 was saved successfully.",
        'msg_error': "An error occurred.",
        'msg_download_stopped': "Download was stopped.",
        'language_label': "Language:"
    }
}
